<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manipulator">
<!--0.5624 height to start-->
<material name="white">
  <color rgba="1 1 1 1"/>
</material>  

<xacro:property name="MXLength" value="0.0611"/>
<xacro:property name="MXWidth" value="0.0402"/>
<xacro:property name="MXDepth" value="0.041"/>

<xacro:property name="MXLengthAxisShort" value="0.013"/>
<xacro:property name="MXLengthAxisLong" value="0.0481"/>

<xacro:property name="MXCouplerThickness" value="0.0025"/>

<xacro:property name="AXLength" value="0.05"/>
<xacro:property name="AXWidth" value="0.032"/>
<xacro:property name="AXDepth" value="0.04"/>

<xacro:property name="LinkLength" value="0.096"/>
<xacro:property name="LinkWidth" value="0.04"/>
<xacro:property name="LinkHeight" value="0.04"/>

<xacro:property name="MXBracketLength" value="0.036"/>

<xacro:property name="AXBracketLength" value="0.052"/>

<xacro:property name="MXBracketCorrection" value="0.002"/>


<!-- MACROS -->

<xacro:macro name="MXInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="0.140" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394" />
  </inertial>
</xacro:macro>

<xacro:macro name="MXVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://mobile_manipulator/meshes/dynamixel_x64series.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="MXCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://mobile_manipulator/meshes/dynamixel_x64series.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>




<xacro:macro name="LinkInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="${0.005*LinkLength}" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394"/>
  </inertial>
</xacro:macro>

<xacro:macro name="LinkVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <box size="0.04 0.04 ${LinkLength}"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="LinkCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <box size="0.04 0.04 ${LinkLength}"/>
      </geometry>    
    </collision> 
</xacro:macro> 
<!--  -->
<xacro:macro name="Link1Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.265" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394"/>
  </inertial>
</xacro:macro>

<xacro:macro name="Link1Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://arm_imitation/meshes/link1.stl" scale="1 1 1"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="Link1Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
      <mesh filename="package://arm_imitation/meshes/link1.stl" scale="1 1 1"/>
    </geometry>    
    </collision> 
</xacro:macro> 

<xacro:macro name="Link2Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="0.265" />
    <inertia ixx="0.000050799110" ixy="0.0" ixz="0.0" iyy="0.00002857215" iyz="0.00000051457" izz="0.000043394"/>
  </inertial>
</xacro:macro>

<xacro:macro name="Link2Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://arm_imitation/meshes/link2.stl" scale="1 1 1"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="Link2Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
      <mesh filename="package://arm_imitation/meshes/link2.stl" scale="1 1 1"/>
    </geometry>    
    </collision> 
</xacro:macro> 

<xacro:macro name="RevJoint" params="id trans rpy parent child axis l u v">
    <joint name="${id}" type="revolute">
      <origin xyz="${trans}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit lower="${l}" upper="${u}" effort="30" velocity="${v}"/>
    </joint>
</xacro:macro> 

<xacro:macro name="FxdJoint" params="id trans rpy parent child">
    <joint name="${id}" type="fixed">
      <origin xyz="${trans}"  rpy="${rpy}" />
      <parent link="${parent}"/>
      <child link="${child}"/> 
    </joint>
</xacro:macro>    

<!-- LINKS -->
<!-- the trans parameter present here is to toggle distance of current object with respect to previous adjacent object i.e. its parent-->
  <link name="base_link">
    <xacro:LinkInertial trans="0 0 0.5624" rpy="0 0 0" />
    <xacro:LinkVisual trans="0 0 0.5624" rpy="0 0 0" />
    <xacro:LinkCollision trans="0 0 0.5624" rpy="0 0 0" />
  </link>

  <link name="shoulder_yaw_motor">
    <xacro:MXInertial trans="0 0 ${MXDepth/2}" rpy="0 0 0 "/>  
    <xacro:MXVisual trans="0 0 ${MXDepth/2}" rpy="0 0 0 "/>
    <xacro:MXCollision trans="0 0 ${MXDepth/2}" rpy="0 0 0"/>
  </link>

  <link name="shoulder_roll_motor">
  <xacro:MXInertial trans="0 ${MXLengthAxisLong} ${MXDepth/2 - MXWidth/2}" rpy="0 0 0 "/>  
  <xacro:MXVisual trans="0 ${MXLengthAxisLong} ${MXDepth/2 - MXWidth/2}" rpy="0 0 0 "/>
  <xacro:MXCollision trans="0 ${MXLengthAxisLong} ${MXDepth/2 - MXWidth/2}" rpy="0 0 0"/>
  </link>

  <link name="shoulder_pitch_motor">
    <xacro:MXInertial trans="0 ${MXLengthAxisLong} 0" rpy="0 0 0"/>  
    <xacro:MXVisual trans="0 ${MXLengthAxisLong} 0" rpy="0.0 0.0 0"/>
    <xacro:MXCollision trans="0 ${MXLengthAxisLong} 0" rpy="0 0 0"/>
  </link>
  
  <link name="link_1">
    <xacro:Link1Inertial trans="0 0 0" rpy="0 0 0"/>  
    <xacro:Link1Visual trans="0 0 0" rpy="0.0 0.0 0"/>
    <xacro:Link1Collision trans="0 0 0" rpy="0 0 0"/>
  </link>

  <link name="link_2">
    <xacro:Link2Inertial trans="0 0 0" rpy="0 0 0"/>  
    <xacro:Link2Visual trans="0 0 0" rpy="0.0 0.0 0"/>
    <xacro:Link2Collision trans="0 0 0" rpy="0 0 0"/>
  </link>



  
 <!-- JOINTS -->
 <!-- the trans parameter present here is to toggle distance of current object with respect to next adjacent object i.e. its child-->
  <xacro:FxdJoint id="base_joint" trans="0 ${LinkWidth/2} 0.5624" rpy="1.57 0 3.14" parent="base_link" child="shoulder_yaw_motor"/>
  <xacro:RevJoint id="shoulder_pitch" trans="0 0 ${MXDepth}" rpy="1.57 0 0" parent="shoulder_yaw_motor" child="shoulder_roll_motor" axis="0 1 0" l="-3.14" u="3.14" v="1.0"/>
  <xacro:RevJoint id="shoulder_roll" trans="0 ${MXLengthAxisLong} ${MXDepth/2}" rpy="1.57 0 1.57" parent="shoulder_roll_motor" child="shoulder_pitch_motor" axis="0 1 0" l="-3.14" u="3.14" v="1.0"/>
  <xacro:RevJoint id="shoulder_yaw" trans="0 ${MXLengthAxisLong} 0" rpy="-1.57 1.57 1.57" parent="shoulder_pitch_motor" child="link_1" axis="-1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <xacro:RevJoint id="elbow_pitch" trans="0 -${MXBracketLength + LinkLength + MXLengthAxisLong} 0" rpy="0 0 0" parent="link_1" child="link_2" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <!-- axis="1 0 0" l="-1.57" u="1.57" v="1.0" -->
  <!-- <xacro:FxdJoint id="biceps_start" trans="0 0 ${MXBracketLength}" rpy="0 0 3.14" parent="shoulder_bracket" child="biscep"/>
  <xacro:FxdJoint id="biceps_end" trans="0 0 ${LinkLength}" rpy="1.57 0 1.57" parent="biscep" child="elbow_motor"/>
  <xacro:RevJoint id="elbow_pitch" trans="0 ${MXLengthAxisLong} 0" rpy="0 1.57 1.57" parent="elbow_motor" child="elbow_bracket" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <xacro:FxdJoint id="forearm_start" trans="0 0 ${MXBracketLength}" rpy="0 0 3.14" parent="elbow_bracket" child="forearm"/>
  <xacro:FxdJoint id="forearm_end" trans="0 0 ${LinkLength}" rpy="1.57 0 1.57" parent="forearm" child="wrist_bracket"/> -->

</robot>
