<?xml version ="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="manipulator">
<!--0.5624 height to start-->
<material name="white">
  <color rgba="1 1 1 1"/>
</material>  

<xacro:property name="MXLength" value="0.0611"/>
<xacro:property name="MXWidth" value="0.0402"/>
<xacro:property name="MXDepth" value="0.041"/>


<xacro:property name="MXLengthAxisShort" value="0.013"/>
<xacro:property name="MXLengthAxisLong" value="0.0481"/>

<xacro:property name="MXCouplerThickness" value="0.0025"/>

<xacro:property name="AXLength" value="0.05"/>
<xacro:property name="AXWidth" value="0.032"/>
<xacro:property name="AXDepth" value="0.04"/>

<xacro:property name="LinkLength" value="0.096"/>
<xacro:property name="LinkWidth" value="0.04"/>
<xacro:property name="LinkHeight" value="0.04"/>

<xacro:property name="MXBracketLength" value="0.036"/>

<xacro:property name="AXBracketLength" value="0.052"/>

<xacro:property name="MXBracketCorrection" value="0.002"/>

<!-- http://gazebosim.org/tutorials?tut=inertia&cat=build_robot#Rescalingthemomentofinertiavalues -->
<xacro:property name="MXMass" value="0.165"/>
<!-- <xacro:property name="MXVolume" value="0.000070668734375"/> -->

<xacro:property name="Link1Mass" value="0.185"/>
<!-- <xacro:property name="Link1Volume" value="0.000231393781250"/> -->

<xacro:property name="Link2Mass" value="0.2651"/>
<!-- <xacro:property name="Link2Volume" value="0.000173506343750"/> -->



<!-- MACROS -->

<xacro:macro name="MXInertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}" />
    <mass value="${MXMass}" />
    <inertia 
      ixx="3.85605E-05"
      ixy="3.5409E-07"
      ixz="7.7913E-07"
      iyy="6.21555E-05"
      iyz="2.7126E-07"
      izz="5.51265E-05"/>
  </inertial>
</xacro:macro>

<xacro:macro name="MXVisual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://arm_imitation/meshes/mx-64.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>         
  </visual>
</xacro:macro>

<xacro:macro name="MXCollision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
        <mesh filename="package://arm_imitation/meshes/mx-64.stl" scale="0.001 0.001 0.001"/>
      </geometry>    
    </collision> 
</xacro:macro>

<xacro:macro name="Link1Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="${Link1Mass}" />
    <inertia 
      ixx="4.8914E-05"
      ixy="3.46135E-07"
      ixz="-2.24405E-06"
      iyy="9.83275E-05"
      iyz="5.71095E-07"
      izz="9.4054E-05"/>
  </inertial>
</xacro:macro>

<xacro:macro name="Link1Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://arm_imitation/meshes/link3.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="Link1Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
      <mesh filename="package://arm_imitation/meshes/link3.stl" scale="0.001 0.001 0.001"/>
    </geometry>    
    </collision> 
</xacro:macro> 

<xacro:macro name="Link2Inertial" params="trans rpy">
  <inertial>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <mass value="${Link2Mass}" />
    <inertia 
      ixx="0.00021581791"
      ixy="-4.474888E-05"
      ixz="-0.00015723081"
      iyy="0.0009819304"
      iyz="-3.653078E-05"
      izz="0.0010320343"/>
  </inertial>
</xacro:macro>

<xacro:macro name="Link2Visual" params="trans rpy">
  <visual>
    <origin xyz="${trans}" rpy="${rpy}"/>
    <geometry>
      <mesh filename="package://arm_imitation/meshes/link4.stl" scale="0.001 0.001 0.001"/>
    </geometry>
    <material name="white"/>       
  </visual>
</xacro:macro>

<xacro:macro name="Link2Collision" params="trans rpy">
    <collision>
      <origin xyz="${trans}" rpy="${rpy}"/>
      <geometry>
      <mesh filename="package://arm_imitation/meshes/link4.stl" scale="0.001 0.001 0.001"/>
    </geometry>    
    </collision> 
</xacro:macro> 

<xacro:macro name="RevJoint" params="id trans rpy parent child axis l u v">
    <joint name="${id}" type="revolute">
      <origin xyz="${trans}" rpy="${rpy}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <axis xyz="${axis}"/>
      <limit lower="${l}" upper="${u}" effort="30" velocity="${v}"/>
    </joint>
</xacro:macro> 

<xacro:macro name="FxdJoint" params="id trans rpy parent child">
    <joint name="${id}" type="fixed">
      <origin xyz="${trans}"  rpy="${rpy}" />
      <parent link="${parent}"/>
      <child link="${child}"/> 
    </joint>
</xacro:macro>    

<!-- LINKS -->

  <link name="shoulder_pitch_motor">
    <xacro:MXInertial trans="0 0 0" rpy="0 0 0 "/>  
    <xacro:MXVisual trans="0 0 0" rpy="0 0 0 "/>
    <xacro:MXCollision trans="0 0 0" rpy="0 0 0"/>
  </link>

  <link name="shoulder_roll_motor">
    <xacro:MXInertial trans="0 0 ${MXLengthAxisLong}" rpy="0 0 0 "/>  
    <xacro:MXVisual trans="0 0 ${MXLengthAxisLong}" rpy="0 0 0 "/>
    <xacro:MXCollision trans="0 0 ${MXLengthAxisLong}" rpy="0 0 0"/>
  </link>

  <link name="shoulder_yaw_motor">
    <xacro:MXInertial trans="0 0 0" rpy="0 0 0"/>  
    <xacro:MXVisual trans="0 0 0" rpy="0 0 0"/>
    <xacro:MXCollision trans="0 0 0" rpy="0 0 0"/>
  </link>
  
  <link name="link_1">
    <xacro:Link1Inertial trans="0 0 0" rpy="0 0 0"/>  
    <xacro:Link1Visual trans="0 0 0" rpy="0 0 0"/>
    <xacro:Link1Collision trans="0 0 0" rpy="0 0 0"/>
  </link>


  <link name="link_2">
    <xacro:Link2Inertial trans="0 0 0" rpy="0 0 0"/>  
    <xacro:Link2Visual trans="0 0 0" rpy="0 0 0"/>
    <xacro:Link2Collision trans="0 0 0" rpy="0 0 0"/>
  </link>



  
 <!-- JOINTS -->
 <!-- the trans parameter present here is to toggle distance of current object with respect to next adjacent object i.e. its child-->

  <!-- <xacro:RevJoint id="shoulder_pitch" trans="0 ${MXDepth/2} 0" rpy="-1.57 -1.57 0" parent="shoulder_pitch_motor" child="shoulder_roll_motor" axis="0 0 1" l="-3.14" u="3.14" v="1.0"/>
  <xacro:RevJoint id="shoulder_roll" trans="0 ${MXLengthAxisLong + MXDepth/2} ${MXLengthAxisLong}" rpy="1.57 1.57 3.14" parent="shoulder_roll_motor" child="shoulder_yaw_motor" axis="0 0 -1" l="-3.14" u="3.14" v="1.0"/>
  <xacro:RevJoint id="shoulder_yaw" trans="0 0 0" rpy="1.57 0 -1.57" parent="shoulder_yaw_motor" child="link_1" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/>
  <xacro:RevJoint id="elbow_pitch" trans="0 ${MXBracketLength + LinkLength + MXLengthAxisLong} 0" rpy="0 -1.57 0" parent="link_1" child="link_2" axis="1 0 0" l="-1.57" u="1.57" v="1.0"/> -->

  <xacro:RevJoint id="shoulder_pitch" trans="0 ${MXDepth/2} 0" rpy="-1.57 -1.57 0" parent="shoulder_pitch_motor" child="shoulder_roll_motor" axis="0 0 -1" l="-3.14" u="3.14" v="6.28"/>
  <xacro:RevJoint id="shoulder_roll" trans="0 ${MXLengthAxisLong + MXDepth/2} ${MXLengthAxisLong}" rpy="1.57 -1.57 3.14" parent="shoulder_roll_motor" child="shoulder_yaw_motor" axis="0 0 1" l="-3.14" u="3.14" v="6.28"/>
  <xacro:RevJoint id="shoulder_yaw" trans="0 0 0" rpy="1.57 0 1.57" parent="shoulder_yaw_motor" child="link_1" axis="1 0 0" l="-1.57" u="1.57" v="6.28"/>
  <xacro:RevJoint id="elbow_pitch" trans="0 ${MXLengthAxisLong + MXBracketLength} 0" rpy="0 1.57 0" parent="link_1" child="link_2" axis="1 0 0" l="-1.57" u="1.57" v="6.28"/>

</robot>
